version: '3'
networks:
  plg_workspace:
    driver: bridge
services:
  apache:
    build:
      context: ./apache
    ports:
      - "5080:80"
      - "5081:443"
    volumes:
      - ./plugins/TPS:/var/www/html/app/Plugin/SNS_Login
    networks:
      - plg_workspace
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    command: mysqld --user=root
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/eccube4.sql:/docker-entrypoint-initdb.d/eccube4.sql
    environment:
      - MYSQL_DATABASE=eccube4
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - plg_workspace
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "5082:80"
    depends_on:
      - "db"
    networks:
      - plg_workspace