version: '3'
networks:
  plg_workspace:
    driver: bridge
services:
  apache:
    env_file:
      - .env
    image: tabenguyen/eccube4-apache:{EC_WEB_VERSION}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Plugin:/var/www/html/app/Plugin/{PLUGIN_NAME}
    networks:
      - plg_workspace
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    command: mysqld --user=root
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/eccube4.sql:/docker-entrypoint-initdb.d/eccube4.sql
    environment:
      - MYSQL_DATABASE=eccube4
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - plg_workspace
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8081:80"
    depends_on:
      - "db"
    networks:
      - plg_workspace